"""Project Cortex - Project DNA: a persistent, compact knowledge base for a
project, stored in the project itself at ``<project>/.tokensnap/project_dna.json``.

The DNA is the project's "second brain". It has two halves:

* **Static analysis** - tech stack, entry points, folder map, dependencies.
  Generated by scanning the project (reusing :mod:`tokensnap.project_primer`)
  and refreshed at most once per ``dna_update_interval`` seconds, since the
  disk scan is the expensive part.
* **Living memory** - the current focus/goal, recent decisions, and resolved
  issues, distilled from conversations (reusing
  :func:`tokensnap.compressor.build_memory_card`) and updated every session.

The proxy injects a compact rendering of the DNA as an *immutable* Core Memory
system block on the first request of a session (see :mod:`tokensnap.proxy`),
so it is never compressed or truncated - compression only ever touches the
message list, never the system prompt.

Everything here is **best-effort and offline**: a missing/corrupt file or an
unwritable directory degrades to an empty DNA, never an exception on the
proxy's hot path. Storing the DNA inside the project means it travels with the
repo and can be committed and shared.
"""

import json
import os
import re
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from tokensnap import compressor, project_primer
from tokensnap.utils import message_text

# Explicit "Decision: ..." / "Decided: ..." / "Plan: ..." lines. The
# compressor's _DECISION_RE catches phrasings like "we'll use X" but its
# `decision:` branch can't match (a trailing \b never follows the colon), so
# these very common labelled lines slip through - we catch them here.
_DECISION_PREFIX_RE = re.compile(r"(?im)^\s*(?:decision|decided|plan)\s*:\s*(.+)$")

SCHEMA_VERSION = 1
DNA_DIRNAME = ".tokensnap"
DNA_FILENAME = "project_dna.json"

# Caps that keep the DNA (and the tokens it costs) small and bounded.
_MAX_DECISIONS = 15
_MAX_RESOLVED = 15
_MAX_CHANGELOG = 12
_FOCUS_MAX = 400
_CORE_MEMORY_CHAR_CAP = 4000

# Common entry-point filenames, checked at the project root and one level down.
_ENTRY_POINT_NAMES = (
    "main.py", "__main__.py", "app.py", "manage.py", "wsgi.py", "asgi.py",
    "cli.py", "server.py", "index.js", "index.ts", "main.js", "main.ts",
    "main.go", "main.rs", "Main.java", "index.html", "Program.cs",
)


def dna_path(project_dir: str) -> Path:
    """Path to the DNA file for ``project_dir``."""
    return Path(project_dir) / DNA_DIRNAME / DNA_FILENAME


def _empty_dna() -> Dict[str, Any]:
    return {
        "schema": SCHEMA_VERSION,
        "generated_at": 0.0,
        "updated_at": 0.0,
        "static": {},
        "focus": "",
        "decisions": [],
        "resolved_issues": [],
        "changelog": [],
    }


def load_dna(project_dir: str) -> Dict[str, Any]:
    """Return the parsed DNA for ``project_dir``, or an empty DNA if none
    exists or it can't be read. Never raises."""
    if not project_dir:
        return _empty_dna()
    try:
        with open(dna_path(project_dir), "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            return _empty_dna()
        # Fill any missing keys so callers can rely on the full shape.
        merged = _empty_dna()
        merged.update(data)
        return merged
    except (OSError, ValueError):
        return _empty_dna()


def save_dna(project_dir: str, dna: Dict[str, Any]) -> bool:
    """Write ``dna`` to the project's DNA file. Best-effort: returns True on
    success, False (without raising) if the directory can't be written."""
    if not project_dir:
        return False
    try:
        target = dna_path(project_dir)
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8") as f:
            json.dump(dna, f, ensure_ascii=False, indent=2)
        return True
    except OSError:
        return False


def _detect_entry_points(project_dir: str) -> List[str]:
    """Best-effort list of likely entry-point files (root + one level deep)."""
    root = Path(project_dir)
    found: List[str] = []
    try:
        for name in _ENTRY_POINT_NAMES:
            if (root / name).is_file():
                found.append(name)
        # One level down (e.g. src/main.py, cmd/app/main.go) - skip noise dirs.
        for child in sorted(root.iterdir()):
            if not child.is_dir() or child.name in project_primer._IGNORE_DIRS:
                continue
            for name in _ENTRY_POINT_NAMES:
                if (child / name).is_file():
                    found.append("%s/%s" % (child.name, name))
            if len(found) >= 12:
                break
    except OSError:
        pass
    return found[:12]


def get_static_dna(project_dir: str) -> Dict[str, Any]:
    """Scan the project into the static half of the DNA.

    Reuses the Project Primer's scanner for the stack/deps/folder-map/git
    facts, and adds explicit entry-point detection. Never raises."""
    card = project_primer.generate_project_card(project_dir)
    return {
        "project_name": card.get("project_name", ""),
        "language": card.get("language", ""),
        "framework": card.get("framework", ""),
        "key_dependencies": card.get("key_dependencies", []),
        "folder_structure": card.get("folder_structure", []),
        "entry_points": _detect_entry_points(project_dir),
        "git_branch": card.get("git_branch", ""),
        "last_commit_summary": card.get("last_commit_summary", ""),
        "readme_summary": card.get("readme_summary", ""),
    }


def ensure_dna(
    project_dir: str, cfg: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """Load the DNA, generating/refreshing the static half if it's missing or
    older than ``dna_update_interval``. Persists any change. Returns the DNA.

    Returns an empty DNA (without writing) when ``project_dir`` isn't a real
    directory - e.g. an untagged 'unknown' session."""
    if not project_dir or not os.path.isdir(project_dir):
        return _empty_dna()
    cfg = cfg or {}
    interval = int(cfg.get("dna_update_interval", 86400) or 0)
    dna = load_dna(project_dir)
    stale = (
        not dna.get("static")
        or (time.time() - float(dna.get("generated_at") or 0)) >= interval
    )
    if stale:
        dna["static"] = get_static_dna(project_dir)
        now = time.time()
        dna["generated_at"] = now
        if not dna.get("updated_at"):
            dna["updated_at"] = now
        save_dna(project_dir, dna)
    return dna


def set_focus(project_dir: str, focus: str) -> Dict[str, Any]:
    """Set the project's current focus/goal and persist it. Returns the DNA."""
    dna = ensure_dna(project_dir)
    dna["focus"] = (focus or "").strip()[:_FOCUS_MAX]
    dna["updated_at"] = time.time()
    save_dna(project_dir, dna)
    return dna


def _merge_unique(existing, new_items, cap, key=None):
    """Append new items not already present, keeping the most recent ``cap``.

    ``key`` maps an item to its identity; it defaults to the full item. For
    timestamped records (decisions, resolved issues) pass ``key`` so the same
    fact seen again in a later session isn't re-added just because its
    timestamp differs."""
    if key is None:
        key = lambda x: json.dumps(x, sort_keys=True)  # noqa: E731
    out = list(existing)
    seen = {key(x) for x in out}
    for item in new_items:
        k = key(item)
        if k not in seen:
            seen.add(k)
            out.append(item)
    return out[-cap:]


def _extract_labelled_decisions(messages: List[Dict[str, Any]]) -> List[str]:
    """Catch explicit "Decision:/Decided:/Plan: ..." lines the compressor's
    regex misses, so a labelled decision is never silently dropped."""
    out: List[str] = []
    for msg in messages:
        for m in _DECISION_PREFIX_RE.finditer(message_text(msg)):
            text = compressor._clip("Decision: " + m.group(1).strip())
            if text not in out:
                out.append(text)
    return out


def _extract_resolved_issues(messages: List[Dict[str, Any]]) -> List[str]:
    """Pair error mentions with a later resolution across the *whole* session.

    ``compressor.build_memory_card`` only pairs an error with a fix inside one
    message; but in practice an error is reported in one message and fixed a
    couple of messages later. This flattens the conversation into a single line
    stream and pairs across that boundary, so the DNA's "resolved issues"
    actually captures the report->fix arc. Reuses the compressor's regexes so
    both modules agree on what counts as an error / a resolution."""
    lines: List[str] = []
    for msg in messages:
        for line in message_text(msg).split("\n"):
            if line.strip():
                lines.append(line)

    resolved: List[str] = []
    pending: Optional[str] = None
    pending_age = 0
    for line in lines:
        if compressor._ERROR_RE.search(line):
            pending = compressor._clip(line)
            pending_age = 0
        elif pending is not None:
            pending_age += 1
            if compressor._RESOLVED_RE.search(line):
                entry = "%s -> %s" % (pending, compressor._clip(line))
                if entry not in resolved:
                    resolved.append(entry)
                pending = None
            elif pending_age > 12:  # give cross-message fixes room, then drop
                pending = None
    return resolved[:_MAX_RESOLVED]


def update_dna_from_session(
    project_dir: str,
    messages: List[Dict[str, Any]],
    cfg: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Distill decisions, resolved issues, and touched files from a session's
    messages into the living half of the DNA, and persist it.

    Reuses :func:`compressor.build_memory_card` for extraction, so the DNA and
    the Memory Card agree on what "a decision" or "a resolved error" is. Purely
    additive and deduplicated; each list is capped. Never raises."""
    if not project_dir or not os.path.isdir(project_dir):
        return _empty_dna()
    dna = ensure_dna(project_dir, cfg)
    try:
        # Regex-only extraction here (llm_cfg=None): fast, offline, and the DNA
        # update runs at session end where latency doesn't matter but hangs do.
        card = compressor.build_memory_card(messages, llm_cfg=None)
    except Exception:  # noqa: BLE001 - a DNA update must never break anything
        return dna

    now = time.time()
    # Union the compressor's decisions with explicit "Decision:" lines it can't
    # match, de-duplicated in order.
    decision_texts = list(card.get("decisions", []))
    for text in _extract_labelled_decisions(messages):
        if text not in decision_texts:
            decision_texts.append(text)
    decisions = [{"at": now, "text": d} for d in decision_texts]
    # Prefer whole-session pairing; fall back to the card's in-message pairs.
    resolved_texts = _extract_resolved_issues(messages) or card.get("errors_resolved", [])
    resolved = [{"at": now, "text": e} for e in resolved_texts]
    files = card.get("files_modified", [])

    by_text = lambda x: x.get("text", "")  # noqa: E731
    dna["decisions"] = _merge_unique(
        dna.get("decisions", []), decisions, _MAX_DECISIONS, key=by_text
    )
    dna["resolved_issues"] = _merge_unique(
        dna.get("resolved_issues", []), resolved, _MAX_RESOLVED, key=by_text
    )
    if card.get("task") or files:
        entry = {"at": now, "task": card.get("task", ""), "files": files[:15]}
        dna["changelog"] = _merge_unique(
            dna.get("changelog", []), [entry], _MAX_CHANGELOG
        )
    dna["updated_at"] = now
    save_dna(project_dir, dna)
    return dna


def format_core_memory(dna: Dict[str, Any]) -> str:
    """Render the DNA as an immutable "Core Memory" system-prompt block.

    Compact and bounded (<= ~1000 tokens). Returns "" when there's nothing
    worth injecting (an empty DNA)."""
    static = dna.get("static") or {}
    payload: Dict[str, Any] = {}
    if static:
        payload["project"] = {
            k: static[k]
            for k in (
                "project_name", "language", "framework", "key_dependencies",
                "entry_points", "folder_structure", "git_branch",
                "last_commit_summary", "readme_summary",
            )
            if static.get(k)
        }
    if dna.get("focus"):
        payload["current_focus"] = dna["focus"]
    if dna.get("decisions"):
        payload["recent_decisions"] = [d.get("text", "") for d in dna["decisions"]][-8:]
    if dna.get("resolved_issues"):
        payload["resolved_issues"] = [
            r.get("text", "") for r in dna["resolved_issues"]
        ][-8:]
    if not payload:
        return ""

    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    if len(body) > _CORE_MEMORY_CHAR_CAP:
        body = body[:_CORE_MEMORY_CHAR_CAP] + "…"
    return (
        "[TOKENSNAP CORE MEMORY]\n"
        "This is TokenSnap's persistent knowledge base for the project you are "
        "working in - its stack, layout, current focus, and the decisions and "
        "fixes from earlier sessions. Treat it as established, authoritative "
        "context (it is never compressed away). Use it to continue work without "
        "re-deriving the project from scratch:\n" + body
    )
